name: Deliver Tokens To Consumer

on:
  push:
    paths:	
      - 'output/**'

jobs:
  deliver_to_frontend_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deliver Platform Deliverable To Frontend 1
      uses: andstor/copycat-action@v3
      with:
        # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
        # Set the secret in the "src" repository
        personal_token: ${{ secrets.DESIGN_TOKENS_ACCESS }}
        # This is the branch that has the code for this article
        src_branch: main
        src_path: output/js/_variables.js
        dst_owner: andrico1234
        dst_repo_name: design-tokens-test-fe-1
        dst_branch: main
        dst_path: tokens/_variables.js
        username: andrico1234
        email: 17087167+andrico1234@users.noreply.github.com
        commit_message: Update platform deliverable 